name: conectar_frontend
description: "Conéctar"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.6.0"
  flutter: ">=3.32.5"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  url_strategy: ^0.3.0
  dio: ^5.8.0+1
  json_serializable: ^6.9.0
  path_provider: ^2.1.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  provider: ^6.1.5
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/