version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: conectar_db 
    restart: unless-stopped
    environment:
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
